---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/antoniopaolacci/sample-quarkus-app.git
    app.quarkus.io/build-timestamp: 2020-09-25 - 11:05:35 +0000
    app.quarkus.io/commit-id: 17d3d60fac6c60d48d625d28d3fbde2854c33719
  labels:
    app.kubernetes.io/name: department-service
    app.kubernetes.io/version: "1.1"
  name: department-service
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/antoniopaolacci/sample-quarkus-app.git
    app.quarkus.io/build-timestamp: 2020-09-25 - 11:05:35 +0000
    app.quarkus.io/commit-id: 17d3d60fac6c60d48d625d28d3fbde2854c33719
  labels:
    app.kubernetes.io/name: department-service
    app.kubernetes.io/version: "1.1"
  name: department-service
spec:
  ports:
  - name: http
    port: 8083
    targetPort: 8083
  selector:
    app.kubernetes.io/name: department-service
    app.kubernetes.io/version: "1.1"
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/antoniopaolacci/sample-quarkus-app.git
    app.quarkus.io/build-timestamp: 2020-09-25 - 11:05:35 +0000
    app.quarkus.io/commit-id: 17d3d60fac6c60d48d625d28d3fbde2854c33719
  labels:
    app.kubernetes.io/name: department-service
    app.kubernetes.io/version: "1.1"
  name: department-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: department-service
      app.kubernetes.io/version: "1.1"
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: https://github.com/antoniopaolacci/sample-quarkus-app.git
        app.quarkus.io/build-timestamp: 2020-09-25 - 11:05:35 +0000
        app.quarkus.io/commit-id: 17d3d60fac6c60d48d625d28d3fbde2854c33719
      labels:
        app.kubernetes.io/name: department-service
        app.kubernetes.io/version: "1.1"
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: a.paolacci/department-service:1.1
        imagePullPolicy: IfNotPresent
        name: department-service
        ports:
        - containerPort: 8083
          name: http
          protocol: TCP
      serviceAccount: department-service
