apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app-type: demo
    app.kubernetes.io/name: employee-service
    app.kubernetes.io/version: "1.1"
  name: employee-load-balancer
  selfLink: /api/v1/namespaces/default/services/employee
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30850
    port: 8765
    protocol: TCP
    targetPort: 8081
  selector:
    app.kubernetes.io/name: employee-service
    app.kubernetes.io/version: "1.1"
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
