---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: 8081
    app.quarkus.io/commit-id: 17d3d60fac6c60d48d625d28d3fbde2854c33719
    app.quarkus.io/vcs-url: https://github.com/antoniopaolacci/sample-quarkus-app.git
    app.quarkus.io/build-timestamp: 2020-09-28 - 09:44:34 +0000
    app-type: demo
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: employee-service
    app.kubernetes.io/version: 1.1
    app-type: demo
  name: employee-service
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: 8081
    app.quarkus.io/commit-id: 17d3d60fac6c60d48d625d28d3fbde2854c33719
    app.quarkus.io/vcs-url: https://github.com/antoniopaolacci/sample-quarkus-app.git
    app.quarkus.io/build-timestamp: 2020-09-28 - 09:44:34 +0000
    app-type: demo
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: employee-service
    app.kubernetes.io/version: 1.1
    app-type: demo
  name: employee-service
spec:
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/name: employee-service
    app.kubernetes.io/version: 1.1
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: 8081
    app.quarkus.io/commit-id: 17d3d60fac6c60d48d625d28d3fbde2854c33719
    app.quarkus.io/vcs-url: https://github.com/antoniopaolacci/sample-quarkus-app.git
    app.quarkus.io/build-timestamp: 2020-09-28 - 09:44:34 +0000
    app-type: demo
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: employee-service
    app.kubernetes.io/version: 1.1
    app-type: demo
  name: employee-service:view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
- kind: ServiceAccount
  name: employee-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: 8081
    app.quarkus.io/commit-id: 17d3d60fac6c60d48d625d28d3fbde2854c33719
    app.quarkus.io/vcs-url: https://github.com/antoniopaolacci/sample-quarkus-app.git
    app.quarkus.io/build-timestamp: 2020-09-28 - 09:44:34 +0000
    app-type: demo
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: employee-service
    app.kubernetes.io/version: 1.1
    app-type: demo
  name: employee-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: employee-service
      app.kubernetes.io/version: 1.1
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: 8081
        app.quarkus.io/commit-id: 17d3d60fac6c60d48d625d28d3fbde2854c33719
        app.quarkus.io/vcs-url: https://github.com/antoniopaolacci/sample-quarkus-app.git
        app.quarkus.io/build-timestamp: 2020-09-28 - 09:44:34 +0000
        app-type: demo
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: employee-service
        app.kubernetes.io/version: 1.1
        app-type: demo
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - secretRef:
            name: postgres-secret
        - configMapRef:
            name: postgres-config
        - configMapRef:
            name: employee-config
        image: antoniopaolacci/employee-service:1.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/live
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: employee-service
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/ready
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
      serviceAccount: employee-service
