---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8085"
    app.quarkus.io/commit-id: 17d3d60fac6c60d48d625d28d3fbde2854c33719
    app.quarkus.io/vcs-url: https://github.com/antoniopaolacci/sample-quarkus-app.git
    app.quarkus.io/build-timestamp: 2020-09-28 - 13:52:10 +0000
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: organization-service
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: organization-service
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8085"
    app.quarkus.io/commit-id: 17d3d60fac6c60d48d625d28d3fbde2854c33719
    app.quarkus.io/vcs-url: https://github.com/antoniopaolacci/sample-quarkus-app.git
    app.quarkus.io/build-timestamp: 2020-09-28 - 13:52:10 +0000
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: organization-service
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: organization-service
spec:
  ports:
  - name: http
    port: 8085
    targetPort: 8085
  selector:
    app.kubernetes.io/name: organization-service
    app.kubernetes.io/version: 1.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8085"
    app.quarkus.io/commit-id: 17d3d60fac6c60d48d625d28d3fbde2854c33719
    app.quarkus.io/vcs-url: https://github.com/antoniopaolacci/sample-quarkus-app.git
    app.quarkus.io/build-timestamp: 2020-09-28 - 13:52:10 +0000
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: organization-service
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: organization-service:view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
- kind: ServiceAccount
  name: organization-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8085"
    app.quarkus.io/commit-id: 17d3d60fac6c60d48d625d28d3fbde2854c33719
    app.quarkus.io/vcs-url: https://github.com/antoniopaolacci/sample-quarkus-app.git
    app.quarkus.io/build-timestamp: 2020-09-28 - 13:52:10 +0000
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: organization-service
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: organization-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: organization-service
      app.kubernetes.io/version: 1.0-SNAPSHOT
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8085"
        app.quarkus.io/commit-id: 17d3d60fac6c60d48d625d28d3fbde2854c33719
        app.quarkus.io/vcs-url: https://github.com/antoniopaolacci/sample-quarkus-app.git
        app.quarkus.io/build-timestamp: 2020-09-28 - 13:52:10 +0000
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: organization-service
        app.kubernetes.io/version: 1.0-SNAPSHOT
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: a.paolacci/organization-service:1.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/live
            port: 8085
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: organization-service
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/ready
            port: 8085
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
      serviceAccount: organization-service
